src/Entity/Firma.php
<?php

namespace App\Entity;

use App\Repository\FirmaRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FirmaRepository::class)]
class Firma
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nazwa = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $NIP = null;

    #[ORM\Column(length: 6, nullable: true)]
    private ?string $KodPocztowy = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $Telefon = null;

    #[ORM\Column(length: 320, nullable: true)]
    private ?string $Email = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $PKD = null;

    #[ORM\Column(length: 36)]
    private ?string $Identyfikator = null;

    #[ORM\Column(length: 35)]
    private ?string $Status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNazwa(): ?string
    {
        return $this->Nazwa;
    }

    public function setNazwa(?string $Nazwa): static
    {
        $this->Nazwa = $Nazwa;

        return $this;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNIP(): ?string
    {
        return $this->NIP;
    }

    public function setNIP(?string $NIP): static
    {
        $this->NIP = $NIP;

        return $this;
    }

    public function getKodPocztowy(): ?string
    {
        return $this->KodPocztowy;
    }

    public function setKodPocztowy(?string $KodPocztowy): static
    {
        $this->KodPocztowy = $KodPocztowy;

        return $this;
    }

    public function getTelefon(): ?string
    {
        return $this->Telefon;
    }

    public function setTelefon(?string $Telefon): static
    {
        $this->Telefon = $Telefon;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPKD(): ?string
    {
        return $this->PKD;
    }

    public function setPKD(string $PKD): static
    {
        $this->PKD = $PKD;

        return $this;
    }

    public function getIdentyfikator(): ?string
    {
        return $this->Identyfikator;
    }

    public function setIdentyfikator(string $Identyfikator): static
    {
        $this->Identyfikator = $Identyfikator;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): static
    {
        $this->Status = $Status;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link rel="manifest" href="{{asset('manifest.json')}}"/>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
		{% block stylesheets %}
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
			<link rel="stylesheet" href="{{ asset('style.css') }}">
		{% endblock %}

		{% block javascripts %}{% endblock %}
	</head>
	<body>
		{% block body %}{% endblock %}
	</body>
</html>

templates/firma.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{% for firma in content.firma %}
		<div class="firma mb-3">
			<h3>{{firma.nazwa}}</h3>
			{% if firma.wlasciciel %}
				<h4>Właściciel</h4>
				<p>Imie:
					{{firma.wlasciciel.imie is defined? firma.wlasciciel.imie : 'brak' }}</p>
				<p>Nazwisko:
					{{firma.wlasciciel.nazwisko is defined? firma.wlasciciel.nazwisko : 'brak' }}</p>
				<p>NIP:
					{{firma.wlasciciel.nip is defined? firma.wlasciciel.nip : 'brak' }}</p>
				<p>Identyfikator REGON:
					{{firma.wlasciciel.regon is defined? firma.wlasciciel.regon : 'brak' }}</p>
			{% endif %}
			<h3>Numer telefonu</h3>
			<p>{{firma.telefon is defined? firma.telefon : 'brak' }}</p>
			<h3>Adres email</h3>
			<p>{{firma.email is defined? firma.email : 'brak' }}</p>
			<h3>Adres www</h3>
			<p>{{firma.www is defined? firma.www : 'brak' }}</p>
			{% if firma.adresDzialalnosci %}
				<h4>Adres</h4>
				<p>Kraj:
					{{firma.adresDzialalnosci.kraj is defined? firma.adresDzialalnosci.kraj : 'brak' }}</p>
				<p>Województwo:
					{{firma.adresDzialalnosci.wojewodztwo is defined? firma.adresDzialalnosci.wojewodztwo : 'brak' }}</p>
				<p>Powiat:
					{{firma.adresDzialalnosci.powiat is defined? firma.adresDzialalnosci.powiat : 'brak' }}</p>
				<p>Gmina:
					{{firma.adresDzialalnosci.gmina is defined? firma.adresDzialalnosci.gmina : 'brak' }}</p>
				<p>Miasto:
					{{firma.adresDzialalnosci.miasto is defined? firma.adresDzialalnosci.miasto : 'brak' }}</p>
				<p>Ulica:
					{{firma.adresDzialalnosci.ulica is defined? firma.adresDzialalnosci.ulica : 'brak' }}</p>
				<p>Budynek:
					{{firma.adresDzialalnosci.budynek is defined? firma.adresDzialalnosci.budynek : 'brak' }}</p>
			{% endif %}
			<h3>Identyfikator rekordu</h3>
			<p>{{firma.id}}</p>
			<h3>Status działalności</h3>
			<p>{{firma.status is defined? firma.status : 'brak' }}</p>
			<h3>Data rozpoczęcia działalności</h3>
			<p>{{firma.dataRozpoczecia is defined? firma.dataRozpoczecia : 'brak' }}</p>
			<h3>Data zakończenia działalności</h3>
			<p>{{firma.dataZakonczenia is defined? firma.dataZakonczenia : 'brak' }}</p>
			<h3>Kod głównego przedmiotu działalności</h3>
			<p>{{firma.pkdGlowny is defined? firma.pkdGlowny : 'brak'}}</p>
			<h3>Lista kodów PKD</h3>
			{% if firma.pkd is defined %}
				{% for item in firma.pkd %}
					<p>{{item}}</p>
				{% endfor %}
			{% else %}
				<p>brak</p>
			{% endif %}
		</div>
	{% endfor %}
{% endblock %}

templates/firmy.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Lista firm
{% endblock %}

{% block body %}

	<h2>
		Znaleziono
		{{content.count}}
		wyników (pokazuje
		{{content.firmy|length}})
	</h2>

	<a href="{{path('eksport')}}?{{app.request.getQueryString}}" class="btn btn-primary">Pobierz</a>

	<div id="firmy" class="m-2">
		{% for firma in content.firmy %}
			<div class="firma mb-3">
				<h3>{{firma.nazwa}}</h3>
				{% if firma.wlasciciel %}
					<h4>Właściciel</h4>
					<p>Imie:
						{{firma.wlasciciel.imie is defined? firma.wlasciciel.imie : 'brak' }}</p>
					<p>Nazwisko:
						{{firma.wlasciciel.nazwisko is defined? firma.wlasciciel.nazwisko : 'brak' }}</p>
					<p>NIP:
						{{firma.wlasciciel.nip is defined? firma.wlasciciel.nip : 'brak' }}</p>
					<p>Identyfikator REGON:
						{{firma.wlasciciel.regon is defined? firma.wlasciciel.regon : 'brak' }}</p>
				{% endif %}
				{% if firma.adresDzialalnosci %}
					<h4>Adres</h4>
					<p>Kraj:
						{{firma.adresDzialalnosci.kraj is defined? firma.adresDzialalnosci.kraj : 'brak' }}</p>
					<p>Województwo:
						{{firma.adresDzialalnosci.wojewodztwo is defined? firma.adresDzialalnosci.wojewodztwo : 'brak' }}</p>
					<p>Powiat:
						{{firma.adresDzialalnosci.powiat is defined? firma.adresDzialalnosci.powiat : 'brak' }}</p>
					<p>Gmina:
						{{firma.adresDzialalnosci.gmina is defined? firma.adresDzialalnosci.gmina : 'brak' }}</p>
					<p>Miasto:
						{{firma.adresDzialalnosci.miasto is defined? firma.adresDzialalnosci.miasto : 'brak' }}</p>
					<p>Ulica:
						{{firma.adresDzialalnosci.ulica is defined? firma.adresDzialalnosci.ulica : 'brak' }}</p>
					<p>Budynek:
						{{firma.adresDzialalnosci.budynek is defined? firma.adresDzialalnosci.budynek : 'brak' }}</p>
				{% endif %}
				<h3>Identyfikator rekordu</h3>
				<p>{{firma.id}}</p>
				<h3>Status działalności</h3>
				<p>{{firma.status is defined? firma.status : 'brak' }}</p>
				<h3>Data rozpoczęcia działalności</h3>
				<p>{{firma.dataRozpoczecia is defined? firma.dataRozpoczecia : 'brak' }}</p>
				<a href="/firma/{{firma.id}}" class="btn btn-primary mt-2">Szczegóły</a>
			</div>
		{% endfor %}
		<div>
			<a class="next btn btn-primary" href="{{app.request.uri}}&page={{query.page is defined ? query.page-1 : 0}}">Poprzedni</a>
			<button class="btn btn-primary">{{query.page is defined ? query.page : 0}}</button>
			<a class="next btn btn-primary" href="{{app.request.uri}}&page={{query.page is defined ? query.page+1 : 1}}">Następny</a>
		</div>
	</div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Wyszukiwanie
{% endblock %}

{% block body %}
	<div class="container mt-2">
		<h1>Wyszukiwanie</h1>
		<form
			action="{{path('firmy')}}">
			{# <h1>Eksport</h1>
											<form action="{{path('eksport')}}"> #}
			<div class="mb-3">
				<label for="imie" class="form-label">Imię</label>
				<input type="text" class="form-control" id="imie" name="imie">
			</div>
			<div class="mb-3">
				<label for="nazwisko" class="form-label">Nazwisko</label>
				<input type="text" class="form-control" id="nazwisko" name="nazwisko">
			</div>
			<div class="mb-3">
				<label for="pkd" class="form-label">Kod PKD</label>
				<input type="text" class="form-control" id="pkd" name="pkd">
				<div class="form-text">W formacie 0123Z</div>
			</div>
			<div class="mb-3">
				<label for="miasto" class="form-label">Miasto</label>
				<input type="text" class="form-control" id="miasto" name="miasto">
			</div>
			<div class="mb-3">
				<label for="dataod" class="form-label">Data rozpoczęcia działalności - zakres dolny</label>
				<input type="date" class="form-control" id="dataod" name="dataod">
			</div>
			<div class="mb-3">
				<label for="status" class="form-label">Status działalności</label>
				<select type="date" class="form-control" id="status" name="status">
					<option></option>
					<option>AKTYWNY</option>
					<option>WYKRESLONY</option>
					<option>ZAWIESZONY</option>
					<option>OCZEKUJE_NA_ROZPOCZECIE_DZIALANOSCI</option>
					<option>WYLACZNIE_W_FORMIE_SPOLKI</option>
				</select>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
{% endblock %}

templates/pobierz.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	{% if procent<100 %}
		<meta http-equiv="refresh" content="300">
	{% endif %}
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Eksportowanie...</h1>
		<progress value="{{progres}}" max="{{pageCount}}"></progress>
	<p>{{procent}}% ({{progres}}/{{pageCount}})</p>
	{# <p>Pozostało ok.
			{{((pageCount - progres)*0.001//1)}}h
			{{((pageCount - progres)*0.06)%60}}min
			{{((pageCount - progres)*3.6)%60}}s
		</p> #}
	{% if procent==100 %}
		<a href="{{path('convert')}}" class="btn btn-primary">Pobierz XLSX</a>
		{# <a href="{{asset('all.json')}}" class="btn btn-secondary">Pobierz JSON</a> #}
	{% else %}
		<a href="{{path('convert')}}" class="btn btn-primary">Pobierz XLSX (częściowo)</a>
	{% endif %}
</div>{% endblock %}